<?php
declare(strict_types=1);

function h(string|null $value): string
{
    return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
}

function app_base_path(): string
{
    static $basePath = null;

    if ($basePath !== null) {
        return $basePath;
    }

    $basePath = '/';
    $scriptPath = (string) ($_SERVER['SCRIPT_NAME'] ?? '');

    if ($scriptPath !== '' && strpos($scriptPath, '/') === 0) {
        $pathParts = explode('/', trim($scriptPath, '/'));
        if (count($pathParts) > 1) {
            // Get the first path segment when the app is hosted in a subfolder.
            $basePath = '/' . $pathParts[0] . '/';
        }
    }

    return $basePath;
}

function asset_url(string $path): string
{
    $assetPath = ltrim($path, '/');
    $url = app_base_path() . $assetPath;
    $filePath = APP_PUBLIC . DIRECTORY_SEPARATOR . str_replace(['/', '\\'], DIRECTORY_SEPARATOR, $assetPath);

    if (is_file($filePath)) {
        $url .= '?v=' . filemtime($filePath);
    }

    return $url;
}

function system_setting_fallbacks(): array
{
    return [
        'organization.university_name' => 'Mindoro State University',
        'organization.campus_name' => 'Bongabong Campus',
        'organization.office_name' => 'Production and Business Operation',
        'organization.system_name' => APP_SYSTEM_NAME,
        'organization.logo_path' => APP_LOGO,
        'organization.address' => '',
        'organization.contact_information' => '',
        'display.sidebar_default_state' => 'expanded',
        'display.default_table_rows' => '10',
        'display.dashboard_default_range' => 'daily',
        'display.theme_color' => 'green-gold',
        'reports.receipt_header' => APP_CAMPUS_NAME,
        'reports.or_number_format' => '0000-{0000}',
        'pos.or_next_sequence' => '1',
        'reports.prepared_by_default' => '',
        'reports.reviewed_by_default' => 'Department Head / Supervisor',
        'reports.approved_by_default' => 'System Administrator',
        'reports.footer_notes' => 'Generated by the Production and Business Operation Record Management System.',
        'reports.confidentiality_note' => 'This document contains sensitive institutional information. Handle with appropriate care.',
        'security.maximum_login_attempts' => (string) LOGIN_MAX_ATTEMPTS,
        'security.account_lock_duration' => (string) LOGIN_LOCKOUT_MINUTES,
        'security.session_timeout' => (string) ((int) (SESSION_IDLE_TIMEOUT_SECONDS / 60)),
        'security.password_minimum_length' => '8',
        'security.require_strong_password' => '1',
        'security.enable_session_logs' => '1',
    ];
}

function app_settings(?PDO $pdo = null, bool $refresh = false): array
{
    static $cache = null;

    if ($cache !== null && !$refresh) {
        return $cache;
    }

    $settings = system_setting_fallbacks();
    if (!$pdo instanceof PDO) {
        $cache = $settings;
        return $settings;
    }

    try {
        $stmt = $pdo->query('SELECT setting_key, setting_value FROM system_settings');
        foreach ($stmt->fetchAll() as $row) {
            $key = (string) ($row['setting_key'] ?? '');
            if ($key === '') {
                continue;
            }
            $settings[$key] = (string) ($row['setting_value'] ?? '');
        }
    } catch (Throwable $e) {
        error_log('System settings load failed: ' . $e->getMessage());
    }

    $cache = $settings;
    return $settings;
}

function app_setting(?PDO $pdo, string $key, ?string $fallback = null): string
{
    $settings = app_settings($pdo);
    $value = trim((string) ($settings[$key] ?? ''));

    if ($value !== '') {
        return $value;
    }

    $fallbacks = system_setting_fallbacks();
    return $fallback ?? (string) ($fallbacks[$key] ?? '');
}

function organization_profile(?PDO $pdo = null): array
{
    $university = app_setting($pdo, 'organization.university_name', 'Mindoro State University');
    $campus = app_setting($pdo, 'organization.campus_name', 'Bongabong Campus');
    $campusName = trim($university . ' ' . $campus);

    $logoPath = trim(app_setting($pdo, 'organization.logo_path', APP_LOGO));

    // Ensure logo path is web-root absolute so it works from routes like /pages/projects.php
    if ($logoPath === '') {
        $logoPath = APP_LOGO;
    }

    if (!preg_match('#^https?://#i', $logoPath)) {
        $basePath = app_base_path();

        if (strpos($logoPath, 'assets/') === 0) {
            $logoPath = $basePath . $logoPath;
        } elseif (strpos($logoPath, '/') !== 0) {
            $logoPath = $basePath . $logoPath;
        }
    }

    return [
        'university_name' => $university,
        'campus_name' => $campus,
        'office_name' => app_setting($pdo, 'organization.office_name', 'Production and Business Operation'),
        'system_name' => app_setting($pdo, 'organization.system_name', APP_SYSTEM_NAME),
        'logo_path' => $logoPath,
        'address' => app_setting($pdo, 'organization.address', ''),
        'contact_information' => app_setting($pdo, 'organization.contact_information', ''),
        'campus_display_name' => $campusName !== '' ? $campusName : APP_CAMPUS_NAME,
    ];
}

function save_system_settings(PDO $pdo, array $settings, array $user): void
{
    $stmt = $pdo->prepare('INSERT INTO system_settings (setting_key, setting_value, updated_by)
        VALUES (:setting_key, :setting_value, :updated_by)
        ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), updated_by = VALUES(updated_by)');

    foreach ($settings as $key => $value) {
        $stmt->execute([
            'setting_key' => substr((string) $key, 0, 100),
            'setting_value' => (string) $value,
            'updated_by' => (int) $user['id'],
        ]);
    }

    app_settings($pdo, true);
}

function redirect(string $path): never
{
    header('Location: ' . $path);
    exit;
}

function set_flash(string $type, string $message): void
{
    $_SESSION['flash'] = [
        'type' => $type,
        'message' => $message,
    ];
}

function get_flash(): ?array
{
    if (!isset($_SESSION['flash'])) {
        return null;
    }

    $flash = $_SESSION['flash'];
    unset($_SESSION['flash']);

    return $flash;
}

function csrf_token(): string
{
    if (empty($_SESSION['csrf_token'])) {
        $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
    }

    return $_SESSION['csrf_token'];
}

function verify_csrf(string $token): bool
{
    return isset($_SESSION['csrf_token']) && hash_equals($_SESSION['csrf_token'], $token);
}

function normalize_datetime_input(?string $value): string
{
    $raw = trim((string) $value);
    if ($raw === '') {
        return date('Y-m-d H:i:s');
    }

    $dt = str_replace('T', ' ', $raw);
    if (strlen($dt) === 16) {
        $dt .= ':00';
    }

    $parsed = DateTime::createFromFormat('Y-m-d H:i:s', $dt);
    if ($parsed === false) {
        return date('Y-m-d H:i:s');
    }

    return $parsed->format('Y-m-d H:i:s');
}

function period_bounds(string $period, ?string $referenceDate = null): array
{
    $ref = new DateTimeImmutable($referenceDate ?: 'now');

    switch ($period) {
        case 'daily':
            $start = $ref->setTime(0, 0, 0);
            $end = $ref->setTime(23, 59, 59);
            break;

        case 'weekly':
            $start = $ref->modify('monday this week')->setTime(0, 0, 0);
            $end = $start->modify('+6 days')->setTime(23, 59, 59);
            break;

        case 'monthly':
            $start = $ref->modify('first day of this month')->setTime(0, 0, 0);
            $end = $ref->modify('last day of this month')->setTime(23, 59, 59);
            break;

        case 'annual':
            $start = $ref->setDate((int) $ref->format('Y'), 1, 1)->setTime(0, 0, 0);
            $end = $ref->setDate((int) $ref->format('Y'), 12, 31)->setTime(23, 59, 59);
            break;

        default:
            $start = $ref->setTime(0, 0, 0);
            $end = $ref->setTime(23, 59, 59);
            break;
    }

    return [$start, $end];
}

function money(float|int|string|null $amount): string
{
    return 'PHP ' . number_format((float) $amount, 2);
}

function product_group_label(string $group): string
{
    return match ($group) {
        'igp' => 'Project Items',
        'service' => 'Services',
        default => 'Products',
    };
}

function product_category_label(string $category, ?string $customCategory = null): string
{
    $customCategory = trim((string) $customCategory);
    if ($customCategory !== '') {
        return $customCategory;
    }

    return match ($category) {
        'school_supply' => 'School Supply',
        'id_supplies' => 'ID Products',
        'id_services' => 'ID Services',
        'printing' => 'Printing Service',
        'photocopy' => 'Photocopy Service',
        'other' => 'Other',
        default => 'Other',
    };
}

function product_category_options(): array
{
    return [
        'school_supply' => 'School Supply',
        'id_supplies' => 'ID Products',
        'id_services' => 'ID Services',
        'printing' => 'Printing Service',
        'photocopy' => 'Photocopy Service',
        'other' => 'Other',
    ];
}

function product_display_name(array $product): string
{
    $name = trim((string) ($product['name'] ?? ''));
    $sku = strtoupper(trim((string) ($product['sku'] ?? '')));

    $knownIdNames = [
        'ID-LACE-001' => 'ID Lace',
        'ID-CARD-001' => 'ID Card',
        'ID-PRINT-001' => 'ID Printing',
        'PRINT-ID' => 'ID Printing',
        'ID-REPLACE-001' => 'ID Replacement',
        'ID-FEE-001' => 'ID Processing Fee',
        'SEED-PRINT-BW' => 'Print Service, Black & White',
        'PRINT-BW-PAPER' => 'Print Service, Black & White',
        'SEED-PRINT-COLOR' => 'Print Service, Colored',
        'SEED-PHOTO-BW' => 'Photocopy Service, Black & White',
        'PHOTO-BW' => 'Photocopy Service, Black & White',
        'SEED-PHOTO-COLOR' => 'Photocopy Service, Colored',
        'PHOTO-COLOR' => 'Photocopy Service, Colored',
    ];
    if (isset($knownIdNames[$sku])) {
        return $knownIdNames[$sku];
    }

    $normalized = strtolower(preg_replace('/[^a-z0-9]+/i', ' ', $name) ?? '');
    $legacyNames = [
        'provide id' => 'ID Processing Fee',
        'sell id' => 'ID Processing Fee',
        'id service' => 'ID Processing Fee',
        'id items' => 'ID Products',
        'photocopy black and white' => 'Photocopy Service, Black & White',
        'photocopy color' => 'Photocopy Service, Colored',
        'photocopy colored' => 'Photocopy Service, Colored',
    ];

    return $legacyNames[trim($normalized)] ?? $name;
}

function normalize_product_category_input(string $categoryInput): array
{
    $categoryInput = trim($categoryInput);
    $options = product_category_options();
    if ($categoryInput === '') {
        return ['category' => 'other', 'category_name' => null];
    }

    if (isset($options[$categoryInput])) {
        return ['category' => $categoryInput, 'category_name' => null];
    }

    $normalizedInput = strtolower(preg_replace('/\s+/', ' ', $categoryInput) ?? '');
    foreach ($options as $value => $label) {
        if ($normalizedInput === strtolower($label)) {
            return ['category' => $value, 'category_name' => null];
        }
    }

    return [
        'category' => 'other',
        'category_name' => substr($categoryInput, 0, 120),
    ];
}

function product_category_requires_expiration(string $categoryLabel): bool
{
    $categoryLabel = strtolower(trim($categoryLabel));
    if ($categoryLabel === '') {
        return false;
    }

    foreach (['consumable', 'food', 'beverage', 'snack', 'bagoong', 'jar'] as $needle) {
        if (str_contains($categoryLabel, $needle)) {
            return true;
        }
    }

    return false;
}

function product_sku_text(array $product): string
{
    return '';
}

function product_type_label(string $type): string
{
    return $type === 'service' ? 'Service' : 'Product';
}

function product_type_for_category(string $category, string $type): string
{
    if (in_array($category, ['printing', 'photocopy', 'id_services'], true)) {
        return 'service';
    }

    return in_array($type, ['item', 'service'], true) ? $type : 'item';
}

function inventory_movement_label(string $movementType): string
{
    return match ($movementType) {
        'opening', 'initial_stock' => 'Opening',
        'stock_in' => 'Stock In',
        'stock_out' => 'Stock Out',
        'sale' => 'Sale',
        'adjustment' => 'Adjustment',
        'damaged' => 'Damaged / Broken',
        'expired' => 'Expired',
        'disposal' => 'Disposal',
        'consumption' => 'Consumed / Used',
        'refill' => 'Ink Refill / Machine Use',
        'void_return' => 'Voided Sale Return',
        default => ucwords(str_replace('_', ' ', $movementType)),
    };
}

function inventory_batch_status(?string $expirationDate): string
{
    if ($expirationDate === null || trim($expirationDate) === '') {
        return 'Good';
    }

    $today = new DateTimeImmutable('today');
    $expiry = DateTimeImmutable::createFromFormat('Y-m-d', $expirationDate) ?: null;
    if ($expiry === null) {
        return 'Good';
    }

    if ($expiry < $today) {
        return 'Expired';
    }

    if ($expiry <= $today->modify('+30 days')) {
        return 'Near Expiry';
    }

    return 'Good';
}

function next_available_pos_or_sequence(PDO $pdo, int $minimum = 1): int
{
    $maxStmt = $pdo->query("SELECT MAX(sequence_no) FROM (
            SELECT CAST(SUBSTRING(or_number, 6) AS UNSIGNED) AS sequence_no FROM sales WHERE or_number REGEXP '^[0-9]{4}-[0-9]{4}$'
            UNION ALL
            SELECT CAST(SUBSTRING(or_number, 6) AS UNSIGNED) AS sequence_no FROM sale_headers WHERE or_number REGEXP '^[0-9]{4}-[0-9]{4}$'
        ) pos_sequences");

    return max($minimum, (int) $maxStmt->fetchColumn() + 1);
}

function generate_pos_or_number(PDO $pdo): string
{
    $ensureStmt = $pdo->prepare('INSERT INTO system_settings (setting_key, setting_value)
        VALUES ("pos.or_next_sequence", "1")
        ON DUPLICATE KEY UPDATE setting_value = setting_value');
    $ensureStmt->execute();

    $stmt = $pdo->prepare('SELECT setting_value FROM system_settings WHERE setting_key = "pos.or_next_sequence" FOR UPDATE');
    $stmt->execute();
    $next = max(1, (int) $stmt->fetchColumn());
    $next = next_available_pos_or_sequence($pdo, $next);

    $orNumber = '0000-' . str_pad((string) $next, 4, '0', STR_PAD_LEFT);
    $updateStmt = $pdo->prepare('INSERT INTO system_settings (setting_key, setting_value)
        VALUES ("pos.or_next_sequence", :next_value)
        ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)');
    $updateStmt->execute(['next_value' => (string) ($next + 1)]);

    return $orNumber;
}

function preview_pos_or_number(PDO $pdo): string
{
    $stmt = $pdo->prepare('SELECT setting_value FROM system_settings WHERE setting_key = "pos.or_next_sequence"');
    $stmt->execute();
    $next = max(1, (int) $stmt->fetchColumn());
    $next = next_available_pos_or_sequence($pdo, $next);

    return '0000-' . str_pad((string) $next, 4, '0', STR_PAD_LEFT);
}

function create_sale_header(PDO $pdo, string $orNumber, string $saleDate, ?int $personId, float $totalAmount, float $totalCost, float $totalProfit, float $paymentAmount, ?string $notes, array $user): int
{
    $paymentStatus = $paymentAmount + 0.0001 >= $totalAmount ? 'paid' : ($paymentAmount > 0 ? 'partial' : 'unpaid');
    $stmt = $pdo->prepare('INSERT INTO sale_headers (or_number, sale_date, person_id, total_amount, total_cost, total_profit, payment_status, notes, created_by)
        VALUES (:or_number, :sale_date, :person_id, :total_amount, :total_cost, :total_profit, :payment_status, :notes, :created_by)');
    $stmt->execute([
        'or_number' => $orNumber !== '' ? $orNumber : null,
        'sale_date' => $saleDate,
        'person_id' => $personId,
        'total_amount' => $totalAmount,
        'total_cost' => $totalCost,
        'total_profit' => $totalProfit,
        'payment_status' => $paymentStatus,
        'notes' => $notes !== '' ? $notes : null,
        'created_by' => (int) $user['id'],
    ]);

    return (int) $pdo->lastInsertId();
}

function create_sale_item(PDO $pdo, int $saleHeaderId, int $legacySaleId, int $productId, int $quantity, float $unitPrice, float $unitCost, float $totalAmount, float $totalCost, float $profit): int
{
    $stmt = $pdo->prepare('INSERT INTO sale_items (sale_header_id, legacy_sale_id, product_id, quantity, unit_price, unit_cost, total_amount, total_cost, profit)
        VALUES (:sale_header_id, :legacy_sale_id, :product_id, :quantity, :unit_price, :unit_cost, :total_amount, :total_cost, :profit)');
    $stmt->execute([
        'sale_header_id' => $saleHeaderId,
        'legacy_sale_id' => $legacySaleId,
        'product_id' => $productId,
        'quantity' => $quantity,
        'unit_price' => $unitPrice,
        'unit_cost' => $unitCost,
        'total_amount' => $totalAmount,
        'total_cost' => $totalCost,
        'profit' => $profit,
    ]);

    return (int) $pdo->lastInsertId();
}

function create_sale_payment(PDO $pdo, int $saleHeaderId, string $paymentDate, float $amount, string $method, ?string $referenceNo, array $user): int
{
    $stmt = $pdo->prepare('INSERT INTO sale_payments (sale_header_id, payment_date, amount, method, reference_no, received_by)
        VALUES (:sale_header_id, :payment_date, :amount, :method, :reference_no, :received_by)');
    $stmt->execute([
        'sale_header_id' => $saleHeaderId,
        'payment_date' => $paymentDate,
        'amount' => $amount,
        'method' => substr(trim($method) !== '' ? trim($method) : 'cash', 0, 40),
        'reference_no' => $referenceNo !== null && trim($referenceNo) !== '' ? trim($referenceNo) : null,
        'received_by' => (int) $user['id'],
    ]);

    return (int) $pdo->lastInsertId();
}

function person_display_label(array $person): string
{
    $parts = [(string) ($person['full_name'] ?? '')];
    if (!empty($person['person_code'])) {
        $parts[] = (string) $person['person_code'];
    }
    if (!empty($person['department'])) {
        $parts[] = (string) $person['department'];
    }
    if (!empty($person['role_or_position'])) {
        $parts[] = (string) $person['role_or_position'];
    }

    return implode(' | ', array_filter($parts, static fn(string $part): bool => trim($part) !== ''));
}

function normalize_person_text(?string $value): string
{
    return preg_replace('/\s+/', ' ', trim((string) $value)) ?? '';
}

function normalize_person_code(?string $value): string
{
    return strtoupper(normalize_person_text($value));
}

function person_duplicate_message(PDO $pdo, string $fullName, string $personCode = '', ?int $excludeId = null): ?string
{
    if ($personCode !== '') {
        $sql = 'SELECT full_name FROM people WHERE person_code = :person_code';
        $params = ['person_code' => $personCode];
        if ($excludeId !== null) {
            $sql .= ' AND id <> :exclude_id';
            $params['exclude_id'] = $excludeId;
        }
        $sql .= ' LIMIT 1';
        $stmt = $pdo->prepare($sql);
        $stmt->execute($params);
        $match = $stmt->fetchColumn();
        if ($match) {
            return 'ID or code already belongs to ' . $match . '. Select the existing person record instead.';
        }
    }

    $sql = 'SELECT person_code FROM people WHERE LOWER(TRIM(full_name)) = LOWER(:full_name)';
    $params = ['full_name' => $fullName];
    if ($excludeId !== null) {
        $sql .= ' AND id <> :exclude_id';
        $params['exclude_id'] = $excludeId;
    }
    $sql .= ' LIMIT 1';
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    $matchCode = $stmt->fetchColumn();
    if ($matchCode !== false) {
        return 'A person with this name already exists' . ($matchCode ? ' under ID/code ' . $matchCode : '') . '. Select the existing record instead.';
    }

    return null;
}

function people_options(PDO $pdo, bool $approvedOnly = true): array
{
    $where = $approvedOnly ? 'WHERE status IN ("approved", "active")' : '';
    $stmt = $pdo->query('SELECT id, full_name, person_code, department, role_or_position, contact_info, status
        FROM people
        ' . $where . '
        ORDER BY full_name ASC, person_code ASC');

    return $stmt->fetchAll();
}

function caretaker_options(PDO $pdo, bool $approvedOnly = true): array
{
    return normalized_person_dropdown_options(people_options($pdo, $approvedOnly));
}

function tenant_options(PDO $pdo, bool $approvedOnly = true): array
{
    return normalized_person_dropdown_options(people_options($pdo, $approvedOnly));
}

function normalized_person_dropdown_options(array $people): array
{
    $options = [];
    $seen = [];
    foreach ($people as $person) {
        $name = trim((string) ($person['full_name'] ?? ''));
        if ($name === '' || strtolower($name) === 'general') {
            continue;
        }
        if (preg_match('/\b(?:pond|stall|booth|kiosk|corner)\s+[a-z0-9-]+$/i', $name) === 1) {
            continue;
        }

        $key = strtolower(person_display_label($person));
        if (isset($seen[$key])) {
            continue;
        }
        $seen[$key] = true;
        $options[] = $person;
    }

    return $options;
}

function product_options(PDO $pdo, bool $activeOnly = true): array
{
    $where = $activeOnly ? 'WHERE p.is_active = 1' : '';
    $stmt = $pdo->query('SELECT
            p.id,
            p.name,
            p.sku,
            p.category,
            p.category_name,
            p.product_group,
            p.type,
            p.stock_qty,
            COALESCE(s.sellable_stock_qty, 0) AS sellable_stock_qty,
            p.cost_price,
            p.selling_price,
            p.is_consumable,
            p.requires_expiration
        FROM products p
        LEFT JOIN (
            SELECT product_id, SUM(quantity_remaining) AS sellable_stock_qty
            FROM inventory_stock_batches
            WHERE quantity_remaining > 0
                AND (expiration_date IS NULL OR expiration_date >= CURDATE())
            GROUP BY product_id
        ) s ON s.product_id = p.id
        ' . $where . '
        ORDER BY p.product_group ASC, p.name ASC, p.sku ASC');

    return $stmt->fetchAll();
}

function pond_options(PDO $pdo, bool $activeOnly = true): array
{
    $where = ['TRIM(p.pond_name) <> ""', 'LOWER(TRIM(p.pond_name)) <> "general"', 'LOWER(TRIM(COALESCE(p.pond_code, ""))) <> "general"'];
    if ($activeOnly) {
        $where[] = 'p.status = "active"';
    }

    $sql = 'SELECT
            p.id,
            p.project_account_id,
            p.id AS account_id,
            p.pond_code,
            p.pond_name,
            p.fish_type,
            p.stock_count,
            p.survival_rate,
            p.fish_growth_stage,
            p.caretaker_id,
            person.full_name AS caretaker_name,
            p.status
        FROM ponds p
        LEFT JOIN people person ON person.id = p.caretaker_id
        WHERE ' . implode(' AND ', $where) . '
        GROUP BY p.id, p.project_account_id, p.pond_code, p.pond_name, p.fish_type, p.stock_count, p.survival_rate, p.fish_growth_stage, p.caretaker_id, person.full_name, p.status
        ORDER BY p.pond_name ASC, p.pond_code ASC';
    $stmt = $pdo->query($sql);

    return $stmt->fetchAll();
}

function find_person(PDO $pdo, int $personId, bool $approvedOnly = true): ?array
{
    if ($personId <= 0) {
        return null;
    }

    $sql = 'SELECT id, full_name, person_code, department, role_or_position, contact_info, status
        FROM people
        WHERE id = :id';
    if ($approvedOnly) {
        $sql .= ' AND status IN ("approved", "active")';
    }

    $stmt = $pdo->prepare($sql);
    $stmt->execute(['id' => $personId]);
    $person = $stmt->fetch();

    return $person ?: null;
}

function render_person_selector(array $people, string $fieldName, string $inputId, ?int $selectedId = null, string $label = 'Person', bool $required = true, array $options = []): void
{
    $selectedPerson = null;
    foreach ($people as $person) {
        if ((int) $person['id'] === (int) $selectedId) {
            $selectedPerson = $person;
            break;
        }
    }

    $listId = $inputId . '_list';
    $targetDepartment = (string) ($options['department_target'] ?? '');
    $targetName = (string) ($options['name_target'] ?? '');
    $targetCode = (string) ($options['code_target'] ?? '');
    $targetRole = (string) ($options['role_target'] ?? '');
    $placeholder = (string) ($options['placeholder'] ?? 'Search by full name, ID, department, or role');
    $addButtonLabel = (string) ($options['add_button_label'] ?? 'Add Proponent');
    $hint = (string) ($options['hint'] ?? 'Select an approved person from the master list.');
    $selectedLabel = $selectedPerson ? person_display_label($selectedPerson) : '';

    echo '<div class="person-selector" data-person-selector data-department-target="' . h($targetDepartment) . '" data-name-target="' . h($targetName) . '" data-code-target="' . h($targetCode) . '" data-role-target="' . h($targetRole) . '">';
    echo '<label for="' . h($inputId) . '">' . h($label) . '</label>';
    echo '<input id="' . h($inputId) . '" type="text" list="' . h($listId) . '" value="' . h($selectedLabel) . '" placeholder="' . h($placeholder) . '" data-person-search' . ($required ? ' required' : '') . ' autocomplete="off">';
    if ($addButtonLabel !== '') {
        echo '<button type="button" class="btn alt mt-2" data-open-modal="' . h((string) ($options['add_modal_id'] ?? 'person-modal')) . '">' . h($addButtonLabel) . '</button>';
    }
    echo '<input type="hidden" name="' . h($fieldName) . '" value="' . h($selectedPerson ? (string) $selectedPerson['id'] : '') . '" data-person-id' . ($required ? ' required' : '') . '>';
    echo '<datalist id="' . h($listId) . '">';
    foreach ($people as $person) {
        echo '<option value="' . h(person_display_label($person)) . '" data-person-id="' . (int) $person['id'] . '" data-full-name="' . h((string) $person['full_name']) . '" data-person-code="' . h((string) ($person['person_code'] ?? '')) . '" data-department="' . h((string) ($person['department'] ?? '')) . '" data-role="' . h((string) ($person['role_or_position'] ?? '')) . '"></option>';
    }
    echo '</datalist>';
    echo '<p class="mt-1 text-xs text-slate-500">' . h($hint) . '</p>';
    echo '</div>';
}

function render_add_person_modal(array $user, string $returnTo, string $modalId = 'person-modal', array $labels = []): void
{
    $isAdmin = $user['role'] === 'admin';
    $adminTitle = (string) ($labels['admin_title'] ?? 'Add Proponent');
    $requestTitle = (string) ($labels['request_title'] ?? 'Request New Proponent');
    $description = (string) ($labels['description'] ?? 'Save the details used by the Project Proponents master list.');
    $submitAdmin = (string) ($labels['submit_admin'] ?? 'Save Proponent');
    $submitRequest = (string) ($labels['submit_request'] ?? 'Submit Request');
    $iconClose = !empty($labels['icon_close']);
    $showCancel = (bool) ($labels['show_cancel'] ?? true);
    echo '<dialog id="' . h($modalId) . '" class="modal modal-wide app-form-modal">';
    echo '<div class="modal-header">';
    echo '<div>';
    echo '<h3>' . h($isAdmin ? $adminTitle : $requestTitle) . '</h3>';
    echo '<p class="mt-1 text-sm text-slate-500">' . h($description) . '</p>';
    echo '</div>';
    echo '<button type="button" class="modal-close" data-close-modal aria-label="Close">' . ($iconClose ? '&times;' : 'Close') . '</button>';
    echo '</div>';
    echo '<form method="post">';
    echo '<input type="hidden" name="csrf_token" value="' . h(csrf_token()) . '">';
    echo '<input type="hidden" name="action" value="add_person">';
    echo '<input type="hidden" name="return_to" value="' . h($returnTo) . '">';
    echo '<div class="form-grid">';
    echo '<div><label for="' . h($modalId) . '_full_name">Full Name *</label><input id="' . h($modalId) . '_full_name" name="full_name" required></div>';
    echo '<div><label for="' . h($modalId) . '_person_code">ID or Code</label><input id="' . h($modalId) . '_person_code" name="person_code" placeholder="Student ID or personnel code"></div>';
    echo '<div><label for="' . h($modalId) . '_department">Department</label><input id="' . h($modalId) . '_department" name="department"></div>';
    echo '<div><label for="' . h($modalId) . '_role">Role or Position</label><input id="' . h($modalId) . '_role" name="role_or_position"></div>';
    echo '<div class="field-wide"><label for="' . h($modalId) . '_contact">Contact Info</label><input id="' . h($modalId) . '_contact" name="contact_info"></div>';

    if ($isAdmin) {
        echo '<div><label for="' . h($modalId) . '_status">Status</label><select id="' . h($modalId) . '_status" name="status"><option value="approved">Approved</option><option value="pending">Pending</option><option value="inactive">Inactive</option></select></div>';
    } else {
        echo '<p class="text-xs text-slate-600 mt-2">New proponent records require admin approval before they can be used.</p>';
    }

    echo '</div>';
    echo '<div class="modal-actions">';
    if ($showCancel) {
        echo '<button type="button" class="btn alt" data-close-modal>Cancel</button>';
    }
    echo '<button type="submit">' . h($isAdmin ? $submitAdmin : $submitRequest) . '</button>';
    echo '</div>';
    echo '</form>';
    echo '</dialog>';
}

function handle_person_post(PDO $pdo, array $user, string $defaultRedirect): bool
{
    $action = (string) ($_POST['action'] ?? '');
    if (!in_array($action, ['add_person', 'update_person'], true)) {
        return false;
    }

    $returnTo = trim((string) ($_POST['return_to'] ?? $defaultRedirect));
    if ($returnTo === '' || str_contains($returnTo, "\n") || str_contains($returnTo, "\r") || preg_match('#^https?://#i', $returnTo)) {
        $returnTo = $defaultRedirect;
    }

    $fullName = normalize_person_text((string) ($_POST['full_name'] ?? ''));
    $personCode = normalize_person_code((string) ($_POST['person_code'] ?? ''));
    $department = normalize_person_text((string) ($_POST['department'] ?? ''));
    $role = normalize_person_text((string) ($_POST['role_or_position'] ?? ''));
    $contact = normalize_person_text((string) ($_POST['contact_info'] ?? ''));

    if ($fullName === '') {
        set_flash('error', 'Full name is required.');
        redirect($returnTo);
    }

    if ($action === 'update_person') {
        // Only Admin can update person records
        if ($user['role'] !== 'admin') {
            set_flash('error', 'You do not have permission to perform this action.');
            redirect($returnTo);
        }

        $personId = (int) ($_POST['person_id'] ?? 0);
        $status = (string) ($_POST['status'] ?? 'pending');
        $status = $status === 'active' ? 'approved' : ($status === 'rejected' ? 'inactive' : $status);

        if ($personId <= 0 || !in_array($status, ['pending', 'approved', 'inactive'], true)) {
            set_flash('error', 'Invalid person update.');
            redirect($returnTo);
        }

        $stmt = $pdo->prepare('SELECT status FROM people WHERE id = :id');
        $stmt->execute(['id' => $personId]);
        $oldPerson = $stmt->fetch();
        if (!$oldPerson) {
            set_flash('error', 'Person not found.');
            redirect($returnTo);
        }
        $oldStatus = $oldPerson['status'];

        $duplicateMessage = person_duplicate_message($pdo, $fullName, $personCode, $personId);
        if ($duplicateMessage !== null) {
            set_flash('error', $duplicateMessage);
            redirect($returnTo);
        }

        $stmt = $pdo->prepare('UPDATE people
            SET full_name = :full_name,
                person_code = :person_code,
                department = :department,
                role_or_position = :role_or_position,
                contact_info = :contact_info,
                status = :status,
                approved_by = CASE WHEN :status = "approved" THEN :approved_by ELSE approved_by END,
                approved_at = CASE WHEN :status = "approved" THEN COALESCE(approved_at, NOW()) ELSE approved_at END
            WHERE id = :id');
        $stmt->execute([
            'id' => $personId,
            'full_name' => $fullName,
            'person_code' => $personCode !== '' ? $personCode : null,
            'department' => $department !== '' ? $department : null,
            'role_or_position' => $role !== '' ? $role : null,
            'contact_info' => $contact !== '' ? $contact : null,
            'status' => $status,
            'approved_by' => (int) $user['id'],
        ]);

        $auditAction = match($status) {
            'approved' => 'person_approved',
            'inactive' => 'person_inactive',
            default => 'person_updated',
        };

        audit_log($pdo, $user, $auditAction, 'people', 'person', $personId, [
            'old_status' => $oldStatus,
            'new_status' => $status,
        ]);

        set_flash('success', 'Proponent record updated: ' . ucfirst($status) . '.');
        redirect($returnTo);
    }

    // Add new person record
    $isAdmin = $user['role'] === 'admin';
    $status = $isAdmin ? (string) ($_POST['status'] ?? 'approved') : 'pending';
    $status = $status === 'active' ? 'approved' : ($status === 'rejected' ? 'inactive' : $status);

    if (!in_array($status, ['pending', 'approved', 'inactive'], true)) {
        $status = $isAdmin ? 'approved' : 'pending';
    }

    $duplicateMessage = person_duplicate_message($pdo, $fullName, $personCode);
    if ($duplicateMessage !== null) {
        set_flash('error', $duplicateMessage);
        redirect($returnTo);
    }

    $stmt = $pdo->prepare('INSERT INTO people (full_name, person_code, department, role_or_position, contact_info, status, created_by, approved_by, approved_at)
        VALUES (:full_name, :person_code, :department, :role_or_position, :contact_info, :status, :created_by, :approved_by, :approved_at)');
    $stmt->execute([
        'full_name' => $fullName,
        'person_code' => $personCode !== '' ? $personCode : null,
        'department' => $department !== '' ? $department : null,
        'role_or_position' => $role !== '' ? $role : null,
        'contact_info' => $contact !== '' ? $contact : null,
        'status' => $status,
        'created_by' => (int) $user['id'],
        'approved_by' => $status === 'approved' ? (int) $user['id'] : null,
        'approved_at' => $status === 'approved' ? date('Y-m-d H:i:s') : null,
    ]);
    $personId = (int) $pdo->lastInsertId();
    audit_log($pdo, $user, 'create_person', 'people', 'person', $personId, ['status' => $status]);

    if ($status === 'approved') {
        set_flash('success', 'Proponent record saved.');
    } else {
        set_flash('success', 'Proponent request submitted for admin approval.');
    }

    redirect($returnTo);
}

function product_group_for_type(string $category, string $type, string $group): string
{
    if ($type === 'service' || in_array($category, ['printing', 'photocopy', 'id_services'], true)) {
        return 'service';
    }

    return in_array($group, ['product', 'igp', 'service'], true) ? $group : 'product';
}

function record_product_price_history(PDO $pdo, int $productId, float $costPrice, float $sellingPrice, ?array $user = null, string $sourceType = 'manual', ?string $notes = null): void
{
    if ($productId <= 0) {
        return;
    }

    $stmt = $pdo->prepare('INSERT INTO product_price_history (product_id, changed_at, cost_price, selling_price, source_type, notes, changed_by)
        VALUES (:product_id, NOW(), :cost_price, :selling_price, :source_type, :notes, :changed_by)');
    $stmt->execute([
        'product_id' => $productId,
        'cost_price' => $costPrice,
        'selling_price' => $sellingPrice,
        'source_type' => substr($sourceType, 0, 40),
        'notes' => $notes !== '' ? $notes : null,
        'changed_by' => isset($user['id']) ? (int) $user['id'] : current_user_id_from_session(),
    ]);
}

function validate_inventory_unit_cost(float $unitCost, float $currentCost = 0.0, float $sellingPrice = 0.0): ?string
{
    if ($unitCost <= 0) {
        return 'Unit cost must be greater than zero for stock-in entries.';
    }

    if ($unitCost > 1000000) {
        return 'Unit cost is too high. Check the amount before saving.';
    }

    if ($currentCost > 0 && ($unitCost < ($currentCost * 0.25) || $unitCost > ($currentCost * 4))) {
        return 'Unit cost is far outside the current inventory cost. Verify the receipt or update pricing first.';
    }

    if ($sellingPrice > 0 && $unitCost > ($sellingPrice * 5)) {
        return 'Unit cost is far above the selling price. Verify the amount before saving.';
    }

    return null;
}

function inventory_weighted_remaining_cost(PDO $pdo, int $productId): ?float
{
    $stmt = $pdo->prepare('SELECT
            COALESCE(SUM(quantity_remaining), 0) AS remaining_qty,
            COALESCE(SUM(quantity_remaining * unit_cost), 0) AS remaining_value
        FROM inventory_stock_batches
        WHERE product_id = :product_id AND quantity_remaining > 0');
    $stmt->execute(['product_id' => $productId]);
    $row = $stmt->fetch() ?: ['remaining_qty' => 0, 'remaining_value' => 0];
    $remainingQty = (int) $row['remaining_qty'];

    if ($remainingQty <= 0) {
        return null;
    }

    return round((float) $row['remaining_value'] / $remainingQty, 2);
}

function inventory_recalculate_product_cost(PDO $pdo, int $productId, ?array $user = null, string $sourceType = 'stock_cost_update'): ?float
{
    $weightedCost = inventory_weighted_remaining_cost($pdo, $productId);
    if ($weightedCost === null) {
        return null;
    }

    $productStmt = $pdo->prepare('SELECT cost_price, selling_price FROM products WHERE id = :id AND is_active = 1');
    $productStmt->execute(['id' => $productId]);
    $product = $productStmt->fetch();
    if (!$product) {
        return null;
    }

    if (round((float) $product['cost_price'], 2) === $weightedCost) {
        return $weightedCost;
    }

    $updateStmt = $pdo->prepare('UPDATE products SET cost_price = :cost_price WHERE id = :id');
    $updateStmt->execute([
        'cost_price' => $weightedCost,
        'id' => $productId,
    ]);

    record_product_price_history($pdo, $productId, $weightedCost, (float) $product['selling_price'], $user, $sourceType, 'Inventory cost recalculated from remaining stock batches');

    return $weightedCost;
}

function inventory_stock_in(PDO $pdo, int $productId, int $quantity, float $unitCost, string $receivedDate, ?string $referenceNo, ?string $notes, ?array $user = null, string $sourceType = 'stock_in', ?string $expirationDate = null, ?string $supplier = null): int
{
    if ($quantity <= 0) {
        return 0;
    }

    $productStmt = $pdo->prepare('SELECT id, type, cost_price, selling_price FROM products WHERE id = :id AND is_active = 1 FOR UPDATE');
    $productStmt->execute(['id' => $productId]);
    $product = $productStmt->fetch();
    if (!$product || $product['type'] !== 'item') {
        throw new RuntimeException('Stock can only be added to active inventory items.');
    }

    $costError = validate_inventory_unit_cost($unitCost, (float) $product['cost_price'], (float) $product['selling_price']);
    if ($costError !== null) {
        throw new RuntimeException($costError);
    }

    $batchCode = ($sourceType === 'opening_balance' ? 'OPEN-' : 'BATCH-') . $productId . '-' . date('YmdHis') . '-' . random_int(100, 999);
    $insertBatch = $pdo->prepare('INSERT INTO inventory_stock_batches (product_id, batch_code, received_date, expiration_date, supplier, quantity_received, quantity_remaining, unit_cost, source_type, reference_no, notes, created_by)
        VALUES (:product_id, :batch_code, :received_date, :expiration_date, :supplier, :quantity_received, :quantity_remaining, :unit_cost, :source_type, :reference_no, :notes, :created_by)');
    $insertBatch->execute([
        'product_id' => $productId,
        'batch_code' => $batchCode,
        'received_date' => $receivedDate,
        'expiration_date' => $expirationDate !== null && trim($expirationDate) !== '' ? trim($expirationDate) : null,
        'supplier' => $supplier !== null && trim($supplier) !== '' ? trim($supplier) : null,
        'quantity_received' => $quantity,
        'quantity_remaining' => $quantity,
        'unit_cost' => $unitCost,
        'source_type' => substr($sourceType, 0, 40),
        'reference_no' => $referenceNo !== '' ? $referenceNo : null,
        'notes' => $notes !== '' ? $notes : null,
        'created_by' => isset($user['id']) ? (int) $user['id'] : current_user_id_from_session(),
    ]);
    $batchId = (int) $pdo->lastInsertId();

    $insertMovement = $pdo->prepare('INSERT INTO inventory_stock_movements (product_id, batch_id, movement_date, movement_type, quantity_change, previous_quantity, new_quantity, unit_cost, total_cost, reference_no, notes, created_by)
        VALUES (:product_id, :batch_id, :movement_date, "stock_in", :quantity_change, :previous_quantity, :new_quantity, :unit_cost, :total_cost, :reference_no, :notes, :created_by)');
    $insertMovement->execute([
        'product_id' => $productId,
        'batch_id' => $batchId,
        'movement_date' => $receivedDate,
        'quantity_change' => $quantity,
        'previous_quantity' => 0,
        'new_quantity' => $quantity,
        'unit_cost' => $unitCost,
        'total_cost' => $unitCost * $quantity,
        'reference_no' => $referenceNo !== '' ? $referenceNo : null,
        'notes' => $notes !== '' ? $notes : null,
        'created_by' => isset($user['id']) ? (int) $user['id'] : current_user_id_from_session(),
    ]);

    $updateProduct = $pdo->prepare('UPDATE products SET stock_qty = stock_qty + :quantity WHERE id = :id');
    $updateProduct->execute([
        'quantity' => $quantity,
        'id' => $productId,
    ]);

    inventory_recalculate_product_cost($pdo, $productId, $user, 'stock_in');

    return $batchId;
}

function inventory_fefo_issue(PDO $pdo, int $productId, int $quantity, string $movementDate, string $movementType, ?string $referenceNo, ?string $notes, ?array $user = null): array
{
    if ($quantity <= 0) {
        throw new RuntimeException('Quantity must be greater than zero.');
    }

    if (!in_array($movementType, ['sale', 'stock_out', 'adjustment', 'damaged', 'expired', 'disposal', 'consumption', 'refill'], true)) {
        throw new RuntimeException('Invalid stock movement type.');
    }

    $productStmt = $pdo->prepare('SELECT id, type, stock_qty FROM products WHERE id = :id AND is_active = 1 FOR UPDATE');
    $productStmt->execute(['id' => $productId]);
    $product = $productStmt->fetch();
    if (!$product || $product['type'] !== 'item') {
        throw new RuntimeException('FEFO stock can only be issued from active inventory items.');
    }

    if ((int) $product['stock_qty'] < $quantity) {
        throw new RuntimeException('Insufficient stock.');
    }

    $batchStmt = $pdo->prepare('SELECT id, quantity_remaining, unit_cost, expiration_date
        FROM inventory_stock_batches
        WHERE product_id = :product_id
            AND quantity_remaining > 0
            AND (expiration_date IS NULL OR expiration_date >= CURDATE())
        ORDER BY expiration_date IS NULL ASC, expiration_date ASC, received_date ASC, id ASC
        FOR UPDATE');
    $batchStmt->execute(['product_id' => $productId]);
    $batches = $batchStmt->fetchAll();

    $remaining = $quantity;
    $totalCost = 0.0;
    $movementIds = [];
    $updateBatch = $pdo->prepare('UPDATE inventory_stock_batches SET quantity_remaining = quantity_remaining - :quantity WHERE id = :id AND quantity_remaining >= :required_quantity');
    $insertMovement = $pdo->prepare('INSERT INTO inventory_stock_movements (product_id, batch_id, movement_date, movement_type, quantity_change, previous_quantity, new_quantity, unit_cost, total_cost, reference_no, notes, created_by)
        VALUES (:product_id, :batch_id, :movement_date, :movement_type, :quantity_change, :previous_quantity, :new_quantity, :unit_cost, :total_cost, :reference_no, :notes, :created_by)');

    foreach ($batches as $batch) {
        if ($remaining <= 0) {
            break;
        }

        $available = (int) $batch['quantity_remaining'];
        $take = min($available, $remaining);
        if ($take <= 0) {
            continue;
        }

        $unitCost = (float) $batch['unit_cost'];
        $newQuantity = $available - $take;
        $layerCost = $unitCost * $take;
        $updateBatch->execute([
            'quantity' => $take,
            'required_quantity' => $take,
            'id' => (int) $batch['id'],
        ]);
        if ($updateBatch->rowCount() === 0) {
            throw new RuntimeException('FEFO stock layer update failed.');
        }

        $insertMovement->execute([
            'product_id' => $productId,
            'batch_id' => (int) $batch['id'],
            'movement_date' => $movementDate,
            'movement_type' => $movementType,
            'quantity_change' => -$take,
            'previous_quantity' => $available,
            'new_quantity' => $newQuantity,
            'unit_cost' => $unitCost,
            'total_cost' => $layerCost,
            'reference_no' => $referenceNo !== '' ? $referenceNo : null,
            'notes' => $notes !== '' ? $notes : null,
            'created_by' => isset($user['id']) ? (int) $user['id'] : current_user_id_from_session(),
        ]);
        $movementIds[] = (int) $pdo->lastInsertId();
        $totalCost += $layerCost;
        $remaining -= $take;
    }

    if ($remaining > 0) {
        throw new RuntimeException('Not enough sellable FEFO stock layers.');
    }

    $updateProduct = $pdo->prepare('UPDATE products SET stock_qty = stock_qty - :quantity WHERE id = :id AND stock_qty >= :required_quantity');
    $updateProduct->execute([
        'quantity' => $quantity,
        'required_quantity' => $quantity,
        'id' => $productId,
    ]);
    if ($updateProduct->rowCount() === 0) {
        throw new RuntimeException('Product stock update failed.');
    }

    inventory_recalculate_product_cost($pdo, $productId, $user, $movementType);

    return [
        'total_cost' => $totalCost,
        'unit_cost' => $quantity > 0 ? $totalCost / $quantity : 0,
        'movement_ids' => $movementIds,
    ];
}

function inventory_fifo_issue(PDO $pdo, int $productId, int $quantity, string $movementDate, string $movementType, ?string $referenceNo, ?string $notes, ?array $user = null): array
{
    return inventory_fefo_issue($pdo, $productId, $quantity, $movementDate, $movementType, $referenceNo, $notes, $user);
}

function date_filter_bounds(string $from, string $to): array
{
    $fromDate = DateTimeImmutable::createFromFormat('Y-m-d H:i:s', $from . ' 00:00:00') ?: new DateTimeImmutable('first day of this month 00:00:00');
    $toDate = DateTimeImmutable::createFromFormat('Y-m-d H:i:s', $to . ' 00:00:00') ?: new DateTimeImmutable('today 00:00:00');

    return [
        $fromDate->format('Y-m-d 00:00:00'),
        $toDate->modify('+1 day')->format('Y-m-d 00:00:00'),
    ];
}

function prefix_search_param(string $value): string
{
    return str_replace(['%', '_'], ['\\%', '\\_'], trim($value)) . '%';
}

function project_account_meta_set(PDO $pdo, int $accountId, string $key, ?string $value): void
{
    $stmt = $pdo->prepare('INSERT INTO project_account_meta (account_id, meta_key, meta_value)
        VALUES (:account_id, :meta_key, :meta_value)
        ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value)');
    $stmt->execute([
        'account_id' => $accountId,
        'meta_key' => substr($key, 0, 80),
        'meta_value' => $value,
    ]);
}

function project_entry_meta_set(PDO $pdo, int $entryId, string $key, ?string $value): void
{
    $stmt = $pdo->prepare('INSERT INTO project_entry_meta (entry_id, meta_key, meta_value)
        VALUES (:entry_id, :meta_key, :meta_value)
        ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value)');
    $stmt->execute([
        'entry_id' => $entryId,
        'meta_key' => substr($key, 0, 80),
        'meta_value' => $value,
    ]);
}

function project_meta_decimal(mixed $value): float
{
    if ($value === null || $value === '') {
        return 0.0;
    }

    return (float) $value;
}

function user_can(array $user, string $permission): bool
{
    $role = strtolower((string) ($user['role'] ?? ''));
    $permissions = [
        'admin' => ['*'],
        'staff' => [
            'view_dashboard',
            'view_operations',
            'record_operations',
            'submit_sensitive_requests',
            'view_reports',
        ],
    ];

    $allowed = $permissions[$role] ?? [];

    return in_array('*', $allowed, true) || in_array($permission, $allowed, true);
}

function user_requires_admin_approval(array $user): bool
{
    return strtolower((string) ($user['role'] ?? '')) !== 'admin';
}

function require_permission(array $user, string $permission, string $fallback = 'dashboard.php'): void
{
    if (user_can($user, $permission)) {
        return;
    }

    set_flash('error', 'Your account does not have permission to access that function.');
    redirect($fallback);
}

function current_request_ip(): string
{
    $ip = (string) ($_SERVER['REMOTE_ADDR'] ?? 'unknown');

    return substr($ip !== '' ? $ip : 'unknown', 0, 45);
}

function current_user_id_from_session(): ?int
{
    return !empty($_SESSION['user_id']) ? (int) $_SESSION['user_id'] : null;
}

function encode_log_context(array|string|null $context): ?string
{
    if ($context === null) {
        return null;
    }

    if (is_string($context)) {
        return $context;
    }

    $encoded = json_encode($context, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

    return $encoded === false ? null : $encoded;
}

function audit_log(PDO $pdo, ?array $user, string $action, string $module, ?string $entityType = null, int|string|null $entityId = null, array|string|null $details = null): void
{
    try {
        $stmt = $pdo->prepare('INSERT INTO audit_logs (user_id, action, module, entity_type, entity_id, details, ip_address)
            VALUES (:user_id, :action, :module, :entity_type, :entity_id, :details, :ip_address)');
        $stmt->execute([
            'user_id' => isset($user['id']) ? (int) $user['id'] : current_user_id_from_session(),
            'action' => substr($action, 0, 80),
            'module' => substr($module, 0, 80),
            'entity_type' => $entityType !== null ? substr($entityType, 0, 80) : null,
            'entity_id' => $entityId !== null ? substr((string) $entityId, 0, 80) : null,
            'details' => encode_log_context($details),
            'ip_address' => current_request_ip(),
        ]);
    } catch (Throwable $e) {
        error_log('Audit log failed: ' . $e->getMessage());
    }
}

function log_system_issue(PDO $pdo, string $severity, string $message, array|string|null $context = null, ?array $user = null): void
{
    $validSeverities = ['notice', 'warning', 'error', 'critical'];
    if (!in_array($severity, $validSeverities, true)) {
        $severity = 'error';
    }

    try {
        $stmt = $pdo->prepare('INSERT INTO system_error_logs (user_id, severity, message, context, ip_address)
            VALUES (:user_id, :severity, :message, :context, :ip_address)');
        $stmt->execute([
            'user_id' => isset($user['id']) ? (int) $user['id'] : current_user_id_from_session(),
            'severity' => $severity,
            'message' => substr($message, 0, 255),
            'context' => encode_log_context($context),
            'ip_address' => current_request_ip(),
        ]);
    } catch (Throwable $e) {
        error_log('System issue log failed: ' . $e->getMessage());
    }
}

function configure_error_logging(PDO $pdo): void
{
    set_error_handler(static function (int $severity, string $message, string $file, int $line) use ($pdo): bool {
        if (!(error_reporting() & $severity)) {
            return false;
        }

        $level = in_array($severity, [E_USER_ERROR, E_RECOVERABLE_ERROR], true) ? 'error' : 'warning';
        log_system_issue($pdo, $level, $message, [
            'file' => $file,
            'line' => $line,
            'severity' => $severity,
        ]);

        return false;
    });

    register_shutdown_function(static function () use ($pdo): void {
        $error = error_get_last();
        if (!$error || !in_array((int) $error['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR], true)) {
            return;
        }

        log_system_issue($pdo, 'critical', (string) $error['message'], [
            'file' => (string) $error['file'],
            'line' => (int) $error['line'],
            'type' => (int) $error['type'],
        ]);
    });
}

function page_param(string $name = 'page'): int
{
    return max(1, (int) ($_GET[$name] ?? 1));
}

function pagination_meta(int $totalRows, int $page, int $perPage): array
{
    $totalPages = max(1, (int) ceil($totalRows / max(1, $perPage)));
    $page = min(max(1, $page), $totalPages);

    return [
        'page' => $page,
        'per_page' => $perPage,
        'total_rows' => $totalRows,
        'total_pages' => $totalPages,
        'offset' => ($page - 1) * $perPage,
    ];
}

function pagination_row_bounds(array $pagination): array
{
    $first = (int) $pagination['offset'] + 1;
    $last = (int) $pagination['offset'] + (int) $pagination['per_page'];

    return [$first, $last];
}

function pagination_url(int $page, string $param = 'page'): string
{
    $query = $_GET;
    $query[$param] = $page;
    $script = basename((string) ($_SERVER['PHP_SELF'] ?? 'index.php'));

    return $script . '?' . http_build_query($query);
}

function render_pagination(array $pagination, string $param = 'page'): void
{
    if ((int) $pagination['total_pages'] <= 1) {
        return;
    }

    $page = (int) $pagination['page'];
    $totalPages = (int) $pagination['total_pages'];

    echo '<nav class="pagination" aria-label="Pagination">';
    echo '<a class="page-link page-link-prev' . ($page <= 1 ? ' disabled' : '') . '" href="' . h(pagination_url(max(1, $page - 1), $param)) . '" aria-label="Previous page">Previous</a>';

    $window = 5;
    $start = max(1, min($page - 2, $totalPages - $window + 1));
    $end = min($totalPages, $start + $window - 1);
    for ($pageNumber = $start; $pageNumber <= $end; $pageNumber++) {
        echo '<a class="page-link' . ($pageNumber === $page ? ' active' : '') . '" href="' . h(pagination_url($pageNumber, $param)) . '" aria-label="Page ' . h((string) $pageNumber) . '">' . h((string) $pageNumber) . '</a>';
    }

    echo '<a class="page-link page-link-next' . ($page >= $totalPages ? ' disabled' : '') . '" href="' . h(pagination_url(min($totalPages, $page + 1), $param)) . '" aria-label="Next page">Next</a>';
    echo '</nav>';
}

// Approval request functions

function create_approval_request(
    PDO $pdo,
    int $requesterId,
    string $module,
    string $actionType,
    ?string $entityType = null,
    ?string $entityId = null,
    array|null $oldValue = null,
    array|null $newValue = null
): int {
    try {
        $stmt = $pdo->prepare('INSERT INTO approval_requests
            (requester_id, module, action_type, entity_type, entity_id, old_value, new_value, status, created_at, updated_at)
            VALUES (:requester_id, :module, :action_type, :entity_type, :entity_id, :old_value, :new_value, "pending", NOW(), NOW())');
        
        $stmt->execute([
            'requester_id' => $requesterId,
            'module' => substr($module, 0, 80),
            'action_type' => substr($actionType, 0, 80),
            'entity_type' => $entityType !== null ? substr($entityType, 0, 80) : null,
            'entity_id' => $entityId !== null ? substr((string) $entityId, 0, 80) : null,
            'old_value' => $oldValue !== null ? json_encode($oldValue, JSON_UNESCAPED_UNICODE) : null,
            'new_value' => $newValue !== null ? json_encode($newValue, JSON_UNESCAPED_UNICODE) : null,
        ]);

        $approvalId = (int) $pdo->lastInsertId();
        
        // Log the approval request creation
        audit_log($pdo, ['id' => $requesterId], 'approval_request_created', $module, $entityType, $entityId, [
            'action_type' => $actionType,
            'approval_id' => $approvalId,
        ]);

        return $approvalId;
    } catch (Throwable $e) {
        error_log('Approval request creation failed: ' . $e->getMessage());
        throw $e;
    }
}

function get_approval_request(PDO $pdo, int $approvalId): ?array
{
    $stmt = $pdo->prepare('SELECT ar.*, u.full_name AS requester_name, u.role AS requester_role,
        du.full_name AS decided_by_name
        FROM approval_requests ar
        LEFT JOIN users u ON u.id = ar.requester_id
        LEFT JOIN users du ON du.id = ar.decided_by_id
        WHERE ar.id = :id');
    
    $stmt->execute(['id' => $approvalId]);
    $result = $stmt->fetch();
    
    if ($result) {
        if ($result['old_value']) {
            $result['old_value'] = json_decode($result['old_value'], true);
        }
        if ($result['new_value']) {
            $result['new_value'] = json_decode($result['new_value'], true);
        }
    }
    
    return $result ?: null;
}

function list_approval_requests(PDO $pdo, ?string $status = 'pending', int $page = 1, int $limit = 50): array
{
    $offset = max(0, ($page - 1) * $limit);
    
    $query = 'SELECT ar.*, u.full_name AS requester_name, u.role AS requester_role,
        du.full_name AS decided_by_name
        FROM approval_requests ar
        LEFT JOIN users u ON u.id = ar.requester_id
        LEFT JOIN users du ON du.id = ar.decided_by_id';
    
    $params = [];
    
    if ($status !== null) {
        $query .= ' WHERE ar.status = :status';
        $params['status'] = $status;
    }
    
    $query .= ' ORDER BY ar.created_at DESC LIMIT :offset, :limit';
    
    $stmt = $pdo->prepare($query);
    foreach ($params as $key => $value) {
        $stmt->bindValue(':' . $key, $value);
    }
    $stmt->bindValue(':offset', $offset, PDO::PARAM_INT);
    $stmt->bindValue(':limit', $limit, PDO::PARAM_INT);
    $stmt->execute();
    
    $results = [];
    while ($row = $stmt->fetch()) {
        if ($row['old_value']) {
            $row['old_value'] = json_decode($row['old_value'], true);
        }
        if ($row['new_value']) {
            $row['new_value'] = json_decode($row['new_value'], true);
        }
        $results[] = $row;
    }
    
    return $results;
}

function decode_approval_row(array $row): array
{
    foreach (['old_value', 'new_value'] as $key) {
        if (!empty($row[$key]) && is_string($row[$key])) {
            $decoded = json_decode((string) $row[$key], true);
            $row[$key] = is_array($decoded) ? $decoded : null;
        }
    }

    return $row;
}

function approval_new_value(array $request): array
{
    return isset($request['new_value']) && is_array($request['new_value'])
        ? $request['new_value']
        : [];
}

function apply_project_account_approval(PDO $pdo, array $request): array
{
    $data = approval_new_value($request);
    $categoryId = (int) ($data['category_id'] ?? 0);
    $accountName = trim((string) ($data['account_name'] ?? ''));

    if ($categoryId <= 0 || $accountName === '') {
        throw new RuntimeException('Approval request is missing account details.');
    }

    if (($data['category_slug'] ?? '') === 'fishpond') {
        $stockCount = trim((string) ($data['fishpond_meta']['stock_count'] ?? '')) !== ''
            ? max(0, (int) $data['fishpond_meta']['stock_count'])
            : null;
        $stmt = $pdo->prepare('INSERT INTO ponds (pond_code, pond_name, fish_type, stock_count, survival_rate, fish_growth_stage, caretaker_id, notes, created_by)
            VALUES (:pond_code, :pond_name, :fish_type, :stock_count, :survival_rate, :fish_growth_stage, :caretaker_id, :notes, :created_by)');
        $stmt->execute([
            'pond_code' => trim((string) ($data['code'] ?? '')) !== '' ? (string) $data['code'] : null,
            'pond_name' => $accountName,
            'fish_type' => trim((string) ($data['fishpond_meta']['fish_type'] ?? '')) !== '' ? (string) $data['fishpond_meta']['fish_type'] : null,
            'stock_count' => $stockCount,
            'survival_rate' => trim((string) ($data['fishpond_meta']['survival_rate'] ?? '')) !== '' ? (string) $data['fishpond_meta']['survival_rate'] : null,
            'fish_growth_stage' => trim((string) ($data['fishpond_meta']['fish_growth_stage'] ?? '')) !== '' ? (string) $data['fishpond_meta']['fish_growth_stage'] : null,
            'caretaker_id' => !empty($data['person_id']) ? (int) $data['person_id'] : null,
            'notes' => trim((string) ($data['notes'] ?? '')) !== '' ? (string) $data['notes'] : null,
            'created_by' => (int) $request['requester_id'],
        ]);
        $pondId = (int) $pdo->lastInsertId();

        audit_log($pdo, ['id' => (int) ($request['decided_by_id'] ?? current_user_id_from_session() ?? 0)], 'approval_applied_pond', 'fishpond', 'pond', $pondId, [
            'approval_id' => (int) $request['id'],
            'requester_id' => (int) $request['requester_id'],
        ]);

        return ['entity_type' => 'pond', 'entity_id' => (string) $pondId];
    }

    $stmt = $pdo->prepare('INSERT INTO project_accounts (category_id, person_id, account_name, code, contact_name, start_date, next_due_date, expected_amount, notes)
        VALUES (:category_id, :person_id, :account_name, :code, :contact_name, :start_date, :next_due_date, :expected_amount, :notes)');
    $stmt->execute([
        'category_id' => $categoryId,
        'person_id' => !empty($data['person_id']) ? (int) $data['person_id'] : null,
        'account_name' => $accountName,
        'code' => trim((string) ($data['code'] ?? '')) !== '' ? (string) $data['code'] : null,
        'contact_name' => trim((string) ($data['contact_name'] ?? '')) !== '' ? (string) $data['contact_name'] : null,
        'start_date' => trim((string) ($data['start_date'] ?? '')) !== '' ? (string) $data['start_date'] : null,
        'next_due_date' => trim((string) ($data['next_due_date'] ?? '')) !== '' ? (string) $data['next_due_date'] : null,
        'expected_amount' => array_key_exists('expected_amount', $data) && $data['expected_amount'] !== null ? (float) $data['expected_amount'] : null,
        'notes' => trim((string) ($data['notes'] ?? '')) !== '' ? (string) $data['notes'] : null,
    ]);
    $accountId = (int) $pdo->lastInsertId();

    $rentalType = trim((string) ($data['rental_type'] ?? ''));
    if (($data['category_slug'] ?? '') === 'rental' && $rentalType !== '') {
        project_account_meta_set($pdo, $accountId, 'rental_type', $rentalType);
    }

    audit_log($pdo, ['id' => (int) ($request['decided_by_id'] ?? current_user_id_from_session() ?? 0)], 'approval_applied_account', 'projects', 'project_account', $accountId, [
        'approval_id' => (int) $request['id'],
        'action_type' => (string) $request['action_type'],
        'requester_id' => (int) $request['requester_id'],
    ]);

    return ['entity_type' => 'project_account', 'entity_id' => (string) $accountId];
}

function apply_project_entry_approval(PDO $pdo, array $request): array
{
    $data = approval_new_value($request);
    $categoryId = (int) ($data['category_id'] ?? 0);
    $entryType = (string) ($data['entry_type'] ?? '');
    $entryDateTime = (string) ($data['entry_datetime'] ?? date('Y-m-d H:i:s'));
    $amount = (float) ($data['amount'] ?? 0);

    if ($categoryId <= 0 || $entryType === '') {
        throw new RuntimeException('Approval request is missing entry details.');
    }

    $categoryStmt = $pdo->prepare('SELECT id, name, slug FROM project_categories WHERE id = :id AND is_active = 1');
    $categoryStmt->execute(['id' => $categoryId]);
    $category = $categoryStmt->fetch();
    if (!$category) {
        throw new RuntimeException('Project category for this approval request no longer exists.');
    }

    $accountId = (int) ($data['account_id'] ?? 0);
    if ($accountId > 0) {
        if ((string) $category['slug'] === 'fishpond') {
            $accountCheck = $pdo->prepare('SELECT id FROM ponds WHERE id = :id');
            $accountCheck->execute(['id' => $accountId]);
        } else {
            $accountCheck = $pdo->prepare('SELECT id FROM project_accounts WHERE id = :id AND category_id = :category_id');
            $accountCheck->execute(['id' => $accountId, 'category_id' => $categoryId]);
        }
        if (!$accountCheck->fetch()) {
            throw new RuntimeException((string) $category['slug'] === 'fishpond' ? 'Selected pond no longer exists.' : 'Selected account no longer belongs to the requested category.');
        }
    }

    if ((string) $category['slug'] === 'fishpond') {
        $meta = is_array($data['fishpond_meta'] ?? null) ? $data['fishpond_meta'] : [];
        $recordType = (string) ($meta['fishpond_record_type'] ?? '');
        $entityType = 'fishpond_record';
        $entityId = null;

        if ($accountId <= 0) {
            throw new RuntimeException('Approval request is missing pond details.');
        }

        if ($recordType === 'feeding') {
            $stmt = $pdo->prepare('INSERT INTO fishpond_feeding_records (pond_id, fed_at, feed_type, quantity, unit, cost, caretaker_id, remarks, created_by)
                VALUES (:pond_id, :fed_at, :feed_type, :quantity, :unit, :cost, :caretaker_id, :remarks, :created_by)');
            $stmt->execute([
                'pond_id' => $accountId,
                'fed_at' => $entryDateTime,
                'feed_type' => trim((string) ($meta['feed_type'] ?? '')) !== '' ? (string) $meta['feed_type'] : null,
                'quantity' => trim((string) ($meta['feed_quantity'] ?? '')) !== '' ? (float) $meta['feed_quantity'] : ($data['quantity'] ?? null),
                'unit' => trim((string) ($data['unit'] ?? '')) !== '' ? (string) $data['unit'] : null,
                'cost' => $amount,
                'caretaker_id' => !empty($meta['caretaker_person_id']) ? (int) $meta['caretaker_person_id'] : null,
                'remarks' => trim((string) ($data['notes'] ?? '')) !== '' ? (string) $data['notes'] : null,
                'created_by' => (int) $request['requester_id'],
            ]);
            $entityType = 'fishpond_feeding_record';
            $entityId = (int) $pdo->lastInsertId();
            $cashDirection = $amount > 0 ? 'out' : null;
            $cashDescription = 'Fishpond feeding';
        } elseif (in_array($recordType, ['stock_movement', 'mortality'], true)) {
            $stmt = $pdo->prepare('INSERT INTO fishpond_stock_movements (pond_id, movement_at, movement_type, quantity, unit, remaining_stock, mortality_count, fish_growth_stage, caretaker_id, remarks, created_by)
                VALUES (:pond_id, :movement_at, :movement_type, :quantity, :unit, :remaining_stock, :mortality_count, :fish_growth_stage, :caretaker_id, :remarks, :created_by)');
            $stmt->execute([
                'pond_id' => $accountId,
                'movement_at' => $entryDateTime,
                'movement_type' => trim((string) ($meta['movement_type'] ?? '')) !== '' ? (string) $meta['movement_type'] : 'Stock Movement',
                'quantity' => array_key_exists('quantity', $data) && $data['quantity'] !== null ? (int) $data['quantity'] : null,
                'unit' => trim((string) ($data['unit'] ?? '')) !== '' ? (string) $data['unit'] : 'fish',
                'remaining_stock' => trim((string) ($meta['remaining_stock'] ?? '')) !== '' ? (int) $meta['remaining_stock'] : null,
                'mortality_count' => trim((string) ($meta['mortality_count'] ?? '')) !== '' ? (int) $meta['mortality_count'] : null,
                'fish_growth_stage' => trim((string) ($meta['fish_growth_stage'] ?? '')) !== '' ? (string) $meta['fish_growth_stage'] : null,
                'caretaker_id' => !empty($meta['caretaker_person_id']) ? (int) $meta['caretaker_person_id'] : null,
                'remarks' => trim((string) ($data['notes'] ?? '')) !== '' ? (string) $data['notes'] : null,
                'created_by' => (int) $request['requester_id'],
            ]);
            $entityType = 'fishpond_stock_movement';
            $entityId = (int) $pdo->lastInsertId();
            $cashDirection = null;
            $cashDescription = 'Fishpond stock movement';
        } elseif ($recordType === 'expense') {
            $stmt = $pdo->prepare('INSERT INTO fishpond_expenses (pond_id, expense_date, expense_type, amount, reference_no, remarks, created_by)
                VALUES (:pond_id, :expense_date, :expense_type, :amount, :reference_no, :remarks, :created_by)');
            $stmt->execute([
                'pond_id' => $accountId,
                'expense_date' => $entryDateTime,
                'expense_type' => trim((string) ($meta['expense_type'] ?? '')) !== '' ? (string) $meta['expense_type'] : null,
                'amount' => $amount,
                'reference_no' => trim((string) ($data['reference_no'] ?? '')) !== '' ? (string) $data['reference_no'] : null,
                'remarks' => trim((string) ($data['notes'] ?? '')) !== '' ? (string) $data['notes'] : null,
                'created_by' => (int) $request['requester_id'],
            ]);
            $entityType = 'fishpond_expense';
            $entityId = (int) $pdo->lastInsertId();
            $cashDirection = $amount > 0 ? 'out' : null;
            $cashDescription = 'Fishpond expense';
        } elseif ($recordType === 'harvest') {
            $stmt = $pdo->prepare('INSERT INTO fishpond_harvest_records (pond_id, harvest_date, kilos, price_per_kilo, total_sales, buyer, remarks, created_by)
                VALUES (:pond_id, :harvest_date, :kilos, :price_per_kilo, :total_sales, :buyer, :remarks, :created_by)');
            $stmt->execute([
                'pond_id' => $accountId,
                'harvest_date' => $entryDateTime,
                'kilos' => trim((string) ($meta['harvest_kilos'] ?? '')) !== '' ? (float) $meta['harvest_kilos'] : ($data['quantity'] ?? null),
                'price_per_kilo' => trim((string) ($meta['price_per_kilo'] ?? '')) !== '' ? (float) $meta['price_per_kilo'] : null,
                'total_sales' => $amount,
                'buyer' => trim((string) ($meta['buyer'] ?? '')) !== '' ? (string) $meta['buyer'] : null,
                'remarks' => trim((string) ($data['notes'] ?? '')) !== '' ? (string) $data['notes'] : null,
                'created_by' => (int) $request['requester_id'],
            ]);
            $entityType = 'fishpond_harvest_record';
            $entityId = (int) $pdo->lastInsertId();
            $cashDirection = $amount > 0 ? 'in' : null;
            $cashDescription = 'Fishpond harvest';
        } else {
            throw new RuntimeException('Approval request has an invalid fishpond record type.');
        }

        if (!empty($cashDirection) && $amount > 0) {
            $insertCash = $pdo->prepare('INSERT INTO cash_transactions (txn_date, direction, source_module, amount, or_number, description, created_by)
                VALUES (:txn_date, :direction, "fishpond", :amount, :or_number, :description, :created_by)');
            $insertCash->execute([
                'txn_date' => $entryDateTime,
                'direction' => $cashDirection,
                'amount' => $amount,
                'or_number' => trim((string) ($data['reference_no'] ?? '')) !== '' ? (string) $data['reference_no'] : null,
                'description' => $cashDescription,
                'created_by' => (int) $request['requester_id'],
            ]);
        }

        audit_log($pdo, ['id' => (int) ($request['decided_by_id'] ?? current_user_id_from_session() ?? 0)], 'approval_applied_fishpond_entry', 'fishpond', $entityType, $entityId, [
            'approval_id' => (int) $request['id'],
            'requester_id' => (int) $request['requester_id'],
        ]);

        return ['entity_type' => $entityType, 'entity_id' => (string) $entityId];
    }

    $insertEntry = $pdo->prepare('INSERT INTO project_entries (category_id, account_id, entry_datetime, entry_type, quantity, unit, amount, reference_no, notes, created_by)
        VALUES (:category_id, :account_id, :entry_datetime, :entry_type, :quantity, :unit, :amount, :reference_no, :notes, :created_by)');
    $insertEntry->execute([
        'category_id' => $categoryId,
        'account_id' => $accountId > 0 ? $accountId : null,
        'entry_datetime' => $entryDateTime,
        'entry_type' => $entryType,
        'quantity' => array_key_exists('quantity', $data) && $data['quantity'] !== null ? (float) $data['quantity'] : null,
        'unit' => trim((string) ($data['unit'] ?? '')) !== '' ? (string) $data['unit'] : null,
        'amount' => $amount,
        'reference_no' => trim((string) ($data['reference_no'] ?? '')) !== '' ? (string) $data['reference_no'] : null,
        'notes' => trim((string) ($data['notes'] ?? '')) !== '' ? (string) $data['notes'] : null,
        'created_by' => (int) $request['requester_id'],
    ]);
    $entryId = (int) $pdo->lastInsertId();

    $syncCash = !empty($data['sync_cash']);
    if ($syncCash && $amount > 0) {
        $direction = null;
        if (in_array($entryType, ['income', 'payment', 'harvest'], true)) {
            $direction = 'in';
        } elseif ($entryType === 'expense') {
            $direction = 'out';
        }

        if ($direction !== null) {
            $insertCash = $pdo->prepare('INSERT INTO cash_transactions (txn_date, direction, source_module, project_entry_id, amount, or_number, description, created_by)
                VALUES (:txn_date, :direction, :source_module, :project_entry_id, :amount, :or_number, :description, :created_by)');
            $insertCash->execute([
                'txn_date' => $entryDateTime,
                'direction' => $direction,
                'source_module' => (string) ($category['slug'] ?: 'projects'),
                'project_entry_id' => $entryId,
                'amount' => $amount,
                'or_number' => trim((string) ($data['reference_no'] ?? '')) !== '' ? (string) $data['reference_no'] : null,
                'description' => (string) $category['name'] . ' - ' . $entryType,
                'created_by' => (int) $request['requester_id'],
            ]);
        }
    }

    $nextDueDate = trim((string) ($data['update_next_due_date'] ?? ''));
    if ($accountId > 0 && $nextDueDate !== '') {
        $updateDue = $pdo->prepare('UPDATE project_accounts SET next_due_date = :next_due_date WHERE id = :id');
        $updateDue->execute(['next_due_date' => $nextDueDate, 'id' => $accountId]);
    }

    audit_log($pdo, ['id' => (int) ($request['decided_by_id'] ?? current_user_id_from_session() ?? 0)], 'approval_applied_entry', 'projects', 'project_entry', $entryId, [
        'approval_id' => (int) $request['id'],
        'requester_id' => (int) $request['requester_id'],
        'entry_type' => $entryType,
        'amount' => $amount,
    ]);

    return ['entity_type' => 'project_entry', 'entity_id' => (string) $entryId];
}

function apply_toga_release_approval(PDO $pdo, array $request): array
{
    $data = approval_new_value($request);
    $categoryId = (int) ($data['category_id'] ?? 0);
    $personId = (int) ($data['person_id'] ?? 0);
    $studentName = trim((string) ($data['student_name'] ?? ''));
    $studentId = trim((string) ($data['student_id'] ?? ''));
    $program = trim((string) ($data['program'] ?? ''));
    $releaseDate = trim((string) ($data['release_date'] ?? date('Y-m-d')));
    $depositAmount = (float) ($data['deposit_amount'] ?? 0);
    $feeAmount = (float) ($data['fee_amount'] ?? 0);
    $totalAmount = $depositAmount + $feeAmount;

    if ($categoryId <= 0 || $personId <= 0 || $studentName === '') {
        throw new RuntimeException('Approval request is missing toga release details.');
    }

    $insertAccount = $pdo->prepare('INSERT INTO project_accounts (category_id, person_id, account_name, code, contact_name, start_date, expected_amount, status, notes)
        VALUES (:category_id, :person_id, :account_name, :code, :contact_name, :start_date, :expected_amount, "active", :notes)');
    $insertAccount->execute([
        'category_id' => $categoryId,
        'person_id' => $personId,
        'account_name' => $studentName,
        'code' => $studentId !== '' ? $studentId : null,
        'contact_name' => $program !== '' ? $program : null,
        'start_date' => $releaseDate,
        'expected_amount' => $totalAmount,
        'notes' => trim((string) ($data['notes'] ?? '')) !== '' ? (string) $data['notes'] : null,
    ]);
    $accountId = (int) $pdo->lastInsertId();

    project_account_meta_set($pdo, $accountId, 'toga_status', 'released');
    project_account_meta_set($pdo, $accountId, 'deposit_amount', number_format($depositAmount, 2, '.', ''));
    project_account_meta_set($pdo, $accountId, 'fee_amount', number_format($feeAmount, 2, '.', ''));
    project_account_meta_set($pdo, $accountId, 'program', $program !== '' ? $program : null);
    project_account_meta_set($pdo, $accountId, 'return_date', null);

    $insertEntry = $pdo->prepare('INSERT INTO project_entries (category_id, account_id, entry_datetime, entry_type, amount, notes, created_by)
        VALUES (:category_id, :account_id, :entry_datetime, "payment", :amount, :notes, :created_by)');
    $insertEntry->execute([
        'category_id' => $categoryId,
        'account_id' => $accountId,
        'entry_datetime' => $releaseDate . ' 00:00:00',
        'amount' => $totalAmount,
        'notes' => trim((string) ($data['notes'] ?? '')) !== '' ? (string) $data['notes'] : 'Toga release fee/deposit',
        'created_by' => (int) $request['requester_id'],
    ]);
    $entryId = (int) $pdo->lastInsertId();
    project_entry_meta_set($pdo, $entryId, 'entry_event', 'toga_release');

    if (!empty($data['sync_cash']) && $totalAmount > 0) {
        $cashStmt = $pdo->prepare('INSERT INTO cash_transactions (txn_date, direction, source_module, project_entry_id, amount, description, created_by)
            VALUES (:txn_date, "in", "toga", :project_entry_id, :amount, :description, :created_by)');
        $cashStmt->execute([
            'txn_date' => $releaseDate . ' 00:00:00',
            'project_entry_id' => $entryId,
            'amount' => $totalAmount,
            'description' => 'Toga release fee/deposit - ' . $studentName,
            'created_by' => (int) $request['requester_id'],
        ]);
    }

    audit_log($pdo, ['id' => (int) ($request['decided_by_id'] ?? current_user_id_from_session() ?? 0)], 'approval_applied_toga_release', 'projects', 'project_account', $accountId, [
        'approval_id' => (int) $request['id'],
        'requester_id' => (int) $request['requester_id'],
    ]);

    return ['entity_type' => 'project_account', 'entity_id' => (string) $accountId];
}

function apply_toga_return_approval(PDO $pdo, array $request): array
{
    $data = approval_new_value($request);
    $accountId = (int) ($data['account_id'] ?? 0);
    $returnDate = trim((string) ($data['return_date'] ?? date('Y-m-d')));
    $refundAmount = (float) ($data['refund_amount'] ?? 0);

    $accountStmt = $pdo->prepare('SELECT pa.id, pa.category_id, pa.account_name
        FROM project_accounts pa
        INNER JOIN project_categories pc ON pc.id = pa.category_id
        WHERE pa.id = :id AND pc.slug = "toga"');
    $accountStmt->execute(['id' => $accountId]);
    $account = $accountStmt->fetch();
    if (!$account) {
        throw new RuntimeException('Toga record for this approval request no longer exists.');
    }

    $update = $pdo->prepare('UPDATE project_accounts SET status = "inactive" WHERE id = :id');
    $update->execute(['id' => $accountId]);
    project_account_meta_set($pdo, $accountId, 'toga_status', 'returned');
    project_account_meta_set($pdo, $accountId, 'return_date', $returnDate);

    $entryType = $refundAmount > 0 ? 'expense' : 'monitoring';
    $insertEntry = $pdo->prepare('INSERT INTO project_entries (category_id, account_id, entry_datetime, entry_type, amount, notes, created_by)
        VALUES (:category_id, :account_id, :entry_datetime, :entry_type, :amount, :notes, :created_by)');
    $insertEntry->execute([
        'category_id' => (int) $account['category_id'],
        'account_id' => $accountId,
        'entry_datetime' => $returnDate . ' 00:00:00',
        'entry_type' => $entryType,
        'amount' => $refundAmount,
        'notes' => $refundAmount > 0 ? 'Toga returned with deposit refund' : 'Toga returned',
        'created_by' => (int) $request['requester_id'],
    ]);
    $entryId = (int) $pdo->lastInsertId();
    project_entry_meta_set($pdo, $entryId, 'entry_event', 'toga_returned');

    if ($refundAmount > 0) {
        $cashStmt = $pdo->prepare('INSERT INTO cash_transactions (txn_date, direction, source_module, project_entry_id, amount, description, created_by)
            VALUES (:txn_date, "out", "toga", :project_entry_id, :amount, :description, :created_by)');
        $cashStmt->execute([
            'txn_date' => $returnDate . ' 00:00:00',
            'project_entry_id' => $entryId,
            'amount' => $refundAmount,
            'description' => 'Toga deposit refund - ' . (string) $account['account_name'],
            'created_by' => (int) $request['requester_id'],
        ]);
    }

    return ['entity_type' => 'project_account', 'entity_id' => (string) $accountId];
}

function apply_toga_forfeit_approval(PDO $pdo, array $request): array
{
    $data = approval_new_value($request);
    $accountId = (int) ($data['account_id'] ?? 0);

    $accountStmt = $pdo->prepare('SELECT pa.id, pa.category_id
        FROM project_accounts pa
        INNER JOIN project_categories pc ON pc.id = pa.category_id
        WHERE pa.id = :id AND pc.slug = "toga"');
    $accountStmt->execute(['id' => $accountId]);
    $account = $accountStmt->fetch();
    if (!$account) {
        throw new RuntimeException('Toga record for this approval request no longer exists.');
    }

    $update = $pdo->prepare('UPDATE project_accounts SET status = "inactive" WHERE id = :id');
    $update->execute(['id' => $accountId]);
    project_account_meta_set($pdo, $accountId, 'toga_status', 'forfeited');

    $insertEntry = $pdo->prepare('INSERT INTO project_entries (category_id, account_id, entry_datetime, entry_type, amount, notes, created_by)
        VALUES (:category_id, :account_id, NOW(), "monitoring", 0, "Toga deposit forfeited", :created_by)');
    $insertEntry->execute([
        'category_id' => (int) $account['category_id'],
        'account_id' => $accountId,
        'created_by' => (int) $request['requester_id'],
    ]);
    $entryId = (int) $pdo->lastInsertId();
    project_entry_meta_set($pdo, $entryId, 'entry_event', 'toga_forfeited');

    return ['entity_type' => 'project_account', 'entity_id' => (string) $accountId];
}

function apply_inventory_stock_movement_approval(PDO $pdo, array $request): array
{
    $data = approval_new_value($request);
    $productId = (int) ($data['product_id'] ?? 0);
    $direction = (string) ($data['direction'] ?? '');
    $quantity = (int) ($data['quantity'] ?? 0);
    $unitCost = (float) ($data['unit_cost'] ?? 0);
    $movementDate = (string) ($data['movement_date'] ?? date('Y-m-d H:i:s'));
    $movementType = (string) ($data['movement_reason'] ?? 'stock_out');
    if (!in_array($movementType, ['stock_out', 'damaged', 'expired', 'disposal', 'consumption', 'refill'], true)) {
        $movementType = 'stock_out';
    }
    $referenceNo = trim((string) ($data['reference_no'] ?? ''));
    $notes = trim((string) ($data['notes'] ?? ''));
    $expirationDate = trim((string) ($data['expiration_date'] ?? ''));
    $postCashOut = !empty($data['post_cash_out']);

    if ($productId <= 0 || $quantity <= 0 || !in_array($direction, ['in', 'out'], true)) {
        throw new RuntimeException('Approval request is missing valid stock movement details.');
    }

    $productStmt = $pdo->prepare('SELECT id, name, type, product_type, cost_price, selling_price, requires_expiration FROM products WHERE id = :id AND type = "item" AND is_active = 1 FOR UPDATE');
    $productStmt->execute(['id' => $productId]);
    $product = $productStmt->fetch();
    if (!$product) {
        throw new RuntimeException('Product is not an active stock item.');
    }

    if ($direction === 'in') {
        $effectiveCost = $unitCost > 0 ? $unitCost : (float) $product['cost_price'];
        $costError = validate_inventory_unit_cost($effectiveCost, (float) $product['cost_price'], (float) $product['selling_price']);
        if ($costError !== null) {
            throw new RuntimeException($costError);
        }
        if (($product['product_type'] ?? 'non_consumable') === 'consumable' && $expirationDate === '') {
            throw new RuntimeException('Expiration date is required for consumable stock.');
        }
        if ((int) ($product['requires_expiration'] ?? 0) === 1 && $expirationDate === '') {
            throw new RuntimeException('Expiration date is required for this item.');
        }

        inventory_stock_in($pdo, $productId, $quantity, $effectiveCost, $movementDate, $referenceNo, $notes, ['id' => (int) $request['requester_id']], 'approved_stock_in', $expirationDate !== '' ? $expirationDate : null);

        if ($postCashOut && $effectiveCost > 0) {
            $cashStmt = $pdo->prepare('INSERT INTO cash_transactions (txn_date, direction, source_module, amount, or_number, description, created_by)
                VALUES (:txn_date, "out", "inventory", :amount, :or_number, :description, :created_by)');
            $cashStmt->execute([
                'txn_date' => $movementDate,
                'amount' => $effectiveCost * $quantity,
                'or_number' => $referenceNo !== '' ? $referenceNo : null,
                'description' => 'Approved stock purchase: ' . (string) $product['name'],
                'created_by' => (int) $request['requester_id'],
            ]);
        }
    } else {
        inventory_fifo_issue($pdo, $productId, $quantity, $movementDate, $movementType, $referenceNo, $notes !== '' ? $notes : inventory_movement_label($movementType), ['id' => (int) $request['requester_id']]);
    }

    audit_log($pdo, ['id' => (int) ($request['decided_by_id'] ?? current_user_id_from_session() ?? 0)], 'approval_applied_stock_movement', 'inventory', 'product', $productId, [
        'approval_id' => (int) $request['id'],
        'direction' => $direction,
        'movement_type' => $direction === 'out' ? $movementType : 'stock_in',
        'quantity' => $quantity,
        'unit_cost' => $unitCost,
    ]);

    return ['entity_type' => 'product', 'entity_id' => (string) $productId];
}

function apply_approval_request_payload(PDO $pdo, array $request): ?array
{
    $module = (string) ($request['module'] ?? '');
    if ($module === 'inventory') {
        return match ((string) ($request['action_type'] ?? '')) {
            'inventory_stock_movement' => apply_inventory_stock_movement_approval($pdo, $request),
            default => null,
        };
    }

    if ($module !== 'projects') {
        return null;
    }

    return match ((string) ($request['action_type'] ?? '')) {
        'add_project_account', 'add_rental_account' => apply_project_account_approval($pdo, $request),
        'record_project_entry' => apply_project_entry_approval($pdo, $request),
        'add_toga_release' => apply_toga_release_approval($pdo, $request),
        'mark_toga_returned' => apply_toga_return_approval($pdo, $request),
        'mark_toga_forfeited' => apply_toga_forfeit_approval($pdo, $request),
        default => null,
    };
}

function approve_approval_request(PDO $pdo, int $approvalId, int $deciderId, ?string $remarks = null): bool
{
    try {
        $startedTransaction = !$pdo->inTransaction();
        if ($startedTransaction) {
            $pdo->beginTransaction();
        }

        $requestStmt = $pdo->prepare('SELECT * FROM approval_requests WHERE id = :id AND status = "pending" FOR UPDATE');
        $requestStmt->execute(['id' => $approvalId]);
        $request = $requestStmt->fetch();
        if (!$request) {
            if ($startedTransaction && $pdo->inTransaction()) {
                $pdo->rollBack();
            }
            return false;
        }

        $request = decode_approval_row($request);
        $request['decided_by_id'] = $deciderId;
        $appliedRecord = apply_approval_request_payload($pdo, $request);
        $entityType = $appliedRecord['entity_type'] ?? ($request['entity_type'] ?? null);
        $entityId = $appliedRecord['entity_id'] ?? ($request['entity_id'] ?? null);

        $stmt = $pdo->prepare('UPDATE approval_requests
            SET status = "approved", admin_decision = "approved", admin_remarks = :remarks,
                decision_date = NOW(), decided_by_id = :decided_by_id, entity_type = :entity_type, entity_id = :entity_id, updated_at = NOW()
            WHERE id = :id AND status = "pending"');
        
        $stmt->execute([
            'id' => $approvalId,
            'decided_by_id' => $deciderId,
            'entity_type' => $entityType,
            'entity_id' => $entityId,
            'remarks' => $remarks,
        ]);
        
        if ($stmt->rowCount() > 0) {
            audit_log($pdo, ['id' => $deciderId], 'approval_request_approved', $request['module'], $request['entity_type'], $request['entity_id'], [
                'approval_id' => $approvalId,
                'action_type' => $request['action_type'],
                'applied_entity_type' => $entityType,
                'applied_entity_id' => $entityId,
            ]);
            if ($startedTransaction && $pdo->inTransaction()) {
                $pdo->commit();
            }
            return true;
        }

        if ($startedTransaction && $pdo->inTransaction()) {
            $pdo->rollBack();
        }
        return false;
    } catch (Throwable $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        error_log('Approval request approval failed: ' . $e->getMessage());
        throw $e;
    }
}

function reject_approval_request(PDO $pdo, int $approvalId, int $deciderId, ?string $remarks = null): bool
{
    try {
        $stmt = $pdo->prepare('UPDATE approval_requests
            SET status = "rejected", admin_decision = "rejected", admin_remarks = :remarks,
                decision_date = NOW(), decided_by_id = :decided_by_id, updated_at = NOW()
            WHERE id = :id AND status = "pending"');
        
        $stmt->execute([
            'id' => $approvalId,
            'decided_by_id' => $deciderId,
            'remarks' => $remarks,
        ]);
        
        if ($stmt->rowCount() > 0) {
            $request = get_approval_request($pdo, $approvalId);
            audit_log($pdo, ['id' => $deciderId], 'approval_request_rejected', $request['module'], $request['entity_type'], $request['entity_id'], [
                'approval_id' => $approvalId,
                'action_type' => $request['action_type'],
            ]);
            return true;
        }
        return false;
    } catch (Throwable $e) {
        error_log('Approval request rejection failed: ' . $e->getMessage());
        throw $e;
    }
}

function request_revision_on_approval(PDO $pdo, int $approvalId, int $deciderId, ?string $remarks = null): bool
{
    try {
        $stmt = $pdo->prepare('UPDATE approval_requests
            SET status = "needs_revision", admin_decision = "needs_revision", admin_remarks = :remarks,
                decision_date = NOW(), decided_by_id = :decided_by_id, updated_at = NOW()
            WHERE id = :id AND status = "pending"');
        
        $stmt->execute([
            'id' => $approvalId,
            'decided_by_id' => $deciderId,
            'remarks' => $remarks,
        ]);
        
        if ($stmt->rowCount() > 0) {
            $request = get_approval_request($pdo, $approvalId);
            audit_log($pdo, ['id' => $deciderId], 'approval_request_revision_requested', $request['module'], $request['entity_type'], $request['entity_id'], [
                'approval_id' => $approvalId,
                'action_type' => $request['action_type'],
            ]);
            return true;
        }
        return false;
    } catch (Throwable $e) {
        error_log('Approval request revision request failed: ' . $e->getMessage());
        throw $e;
    }
}

function count_pending_approvals(PDO $pdo): int
{
    $stmt = $pdo->query('SELECT COUNT(*) FROM approval_requests WHERE status = "pending"');
    return (int) $stmt->fetchColumn();
}
